Update discovering-spicedb.mdx
authzed/docs pull request #216
Opened 2024-03-25 09:04 UTC by KambangSinclaire

Fixed some typing errors

2024-03-25 09:29 UTC, vroldanbet commented
@KambangSinclaire we appreciate the change 🙏🏻  I'm afraid `authzed/docs` are now deprecated - `authzed.com/docs` is now build from a internal repository.

2024-03-25 09:46 UTC, vroldanbet commented
My bad, it appears this is still used as the source of truth for the docs

2024-03-25 21:46 UTC, samkim requested changes

2024-03-25 21:46 UTC, samkim commented on pages/spicedb/getting-started/discovering-spicedb.mdx
> +In the following month, they would write the first API-complete implementation of Zanzibar; project Arrakis was written in lazily evaluated, type-annotated Python.
Please revert, "lazily-evaluated" is intended to be an adjective for Python

2024-03-25 21:46 UTC, samkim commented on pages/spicedb/getting-started/discovering-spicedb.mdx
> +- A flexible consistency model configurable [per request] that includes resistance to the [New Enemy Problem]
Update the associated link definition below on line 69

2024-08-22 11:36 UTC, vroldanbet commented
Closing as stale

2024-08-22 11:36 UTC, closed without merging