Improve tutorial for go.
authzed/docs pull request #76
Opened 2022-11-15 15:27 UTC by ensonic

With go modules we need to run a few extra steps.

2022-11-15 17:26 UTC, vroldanbet requested changes
Thanks for the PR! I'm not sure the intent of those snippets is to have self-contained shell code - you can see snippets for other languages also omit the bits to bootstrap a full-blown application. I _could see_ us adding `go get github.com/authzed/grpcutil`, although it should be optional. @jzelinskie thoughts?

2022-11-15 22:45 UTC, jzelinskie commented
This is tough one: on one hand folks should be able to copy and paste and have things succeed and on the other hand we don't want to be too prescriptive on what tools they should be using.

For example, for Python, we're big fans of tools like pyenv, poetry and everything else pyproject.toml, but that's not a standard toolchain.

I'm leaning towards approving this and so that our instructions are exhaustive enough that folks don't trip up and get confused.

2022-11-16 17:56 UTC, ensonic commented
Really up to you, I see some benefit in making the tutorials super straightforward to follow.

2022-11-17 05:16 UTC, jzelinskie approved these changes

2022-11-17 05:16 UTC, merged

2022-11-17 05:17 UTC, jzelinskie commented
Thanks again for this contribution. It really means a lot to help folks getting started.